### ISSUE TITLE
Can't use azure 

### ISSUE THREAD

**Issue by razaq-yassine** [matthewbdaly/laravel-azure-storage#14]
Hi, I'm new to **Azure storage**. I applied the instructions provided in the ReadMe file.
I don't know how to import or use files in the storage account.
Can you help me set this up so I can use the **Azure storage** file as the main **storage** file

**Comment by matthewbdaly** [comment]
You need to refer to the Laravel docs for this. This is just an Azure-specific adapter for Laravel's file storage API and the documentation for that covers this.
