### ISSUE TITLE
laravel 8 can not install 

### ISSUE THREAD

**Issue by lalpur** [matthewbdaly/laravel-azure-storage#16]
```
problem 1
    - Installation request for matthewbdaly/laravel-azure-storage ^1.3 -> satisfiable by matthewbdaly/laravel-azure-storage[1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.0.1].
```

can not install this package on laravel 8.

can you guide how to install in laravel 8 
thanks

**Comment by matthewbdaly** [comment]
I've made a new release. Can you try this again?

**Comment by lalpur** [comment]
@matthewbdaly  getting a same issue again on laravel v8.4.0

**Comment by Krisell** [comment]
The issue is that https://github.com/Azure/azure-storage-common-php requires `Guzzle 6` whereas `Laravel 8` requires `Guzzle 7`.

**Comment by lalpur** [comment]
@Krisell  yes  so how to fixed this issue?

**Comment by Krisell** [comment]
> @Krisell yes so how to fixed this issue?

In one of these ways:
 1. You wait for someone else to solve the problem
 2. You make a PR to update azure-storage-common to use Guzzle 7
 3. You remove your dependency on `azure-storage-common`

**Comment by matthewbdaly** [comment]
@Krisell Thanks for your input. I haven't had the occasion yet to look into this issue properly so you've saved me the need to dig into this.

@lalpur This package is just a wrapper for Flysystem's Azure driver so I can't  resolve this until that's updated.

Your options are therefore to either downgrade your Laravel install or use an alternative storage provider until such time as Flysystem's Azure driver is updated to use a newer Guzzle version.
