### ISSUE TITLE
Undefined index: endpoint

### ISSUE THREAD

**Issue by mvalee** [matthewbdaly/laravel-azure-storage#19]
```
    "class": "ErrorException",
    "message": "Undefined index: endpoint",
    "code": 0,
    "file": "/www/vendor/matthewbdaly/laravel-azure-storage/src/AzureStorageServiceProvider.php:28",
```

Since upgrade to 1.3.10, the `config/filesystems.php` array for 'azure' MUST contain an 'endpoint' (can be null), otherwise the value is unset and will throw an error at `AzureStorageServiceProvider.php:28`.

**Comment by ingalless** [comment]
@mvalee My bad! I've opened a PR that fixes this

**Comment by matthewbdaly** [comment]
I've pulled in @ingalless's pull request to fix this and released a new version, so this should now be resolved.
