### ISSUE TITLE
setContentType

### ISSUE THREAD

**Issue by ComputerGuruInTraining** [matthewbdaly/laravel-azure-storage#2]
Hi,

This works great for uploading an image, but the content-type is set to "application/octet-stream" which means images will only be downloaded and not open in the user's browser. To open in the browser, the content-type needs to be "image/jpeg". 

I have tried to set the content-type at time of upload, and after the upload on the existing blob but with no success. 

Please could you provide a solution to change the content-type.

Thank you

**Comment by matthewbdaly** [comment]
This appears to be related to [this issue](https://github.com/thephpleague/flysystem/issues/34) in Flysystem, which is what the Laravel filesystem abstraction uses under the bonnet.

It looks like the `put` method [supports a third parameter for the options](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Filesystem/FilesystemAdapter.php), so passing those options through may resolve the problem. If not I'm not sure it can be resolved - third party storage drivers for the Filesystem abstraction have more limited access than those that ship with Laravel, and you might be better off using Flysystem directly.
