### ISSUE TITLE
Soft deleted files being returned

### ISSUE THREAD

**Issue by BrevAlessio** [matthewbdaly/laravel-azure-storage#22]
Hi, since a few days I'm experiencing the following problem: the `files` method returns also soft deleted files. Is there any option to exclude them from the response?

Thank you

**Comment by matthewbdaly** [comment]
I think this is probably an issue to raise in Flysystem's Azure Blob Storage integration. This is basically just a service provider for that, so I don't think there's anything I can do in this package to resolve the issue.
