### ISSUE TITLE
The Share does not exists

### ISSUE THREAD

**Issue by abhijeet9920** [matthewbdaly/laravel-azure-storage#24]
How can I upload file in Azure File Share instead of containers. I have a file which is accessible by multiple application.

**Comment by matthewbdaly** [comment]
You can't. It looks like that functionality is completely separate from blob storage. This is an adapter for blob storage and adding this functionality would be out of scope for the package.

If you need this functionality you will need to either find a different Laravel adapter for it, or find a Flysystem adapter for it and create your own custom storage driver as described in the Laravel documentation.

**Comment by abhijeet9920** [comment]
Ok thanks.
