### ISSUE TITLE
Use Illuminate\Contracts\Container instead of Illuminate\Contracts\Foundation\Application

### ISSUE THREAD

**Issue by kanidjar** [matthewbdaly/laravel-azure-storage#30]
Hi,

We are using Lumen with your library and your commit [628fe40b2154ea0b5545590d3fd92b88e5e830c9](https://github.com/matthewbdaly/laravel-azure-storage/commit/628fe40b2154ea0b5545590d3fd92b88e5e830c9) broke our application.

Could you please use Illuminate\Contracts\Container instead?  Both Laravel and Lumen applications implement Illuminate\Contracts\Container

**Comment by matthewbdaly** [comment]
I've pushed a commit that *should* fix this, but Travis CI is being a bit rubbish right now and not running the test suite.

Can you confirm this fixes the issue for you?

**Comment by kanidjar** [comment]
Confirmed, issue fixed.

Thank you 👍

**Comment by matthewbdaly** [comment]
Excellent. Will therefore close this off.
