### ISSUE TITLE
Does this supports uploading files in chunks directly to Azure Container?

### ISSUE THREAD

**Issue by sammyaxe** [matthewbdaly/laravel-azure-storage#33]
I'm wondering if this package support uploading files as blobs directly to azure?

**Comment by matthewbdaly** [comment]
This package is just a thin wrapper on top of the Flysystem Azure integration to integrate it with Laravel's file storage API, together with a service provider.

As such, I haven't a clue whether you can do that or not. It's entirely dependent on whether the Flysystem Azure integration does.
