### ISSUE TITLE
Blob service REST API

### ISSUE THREAD

**Issue by brpetrov** [matthewbdaly/laravel-azure-storage#35]
Hi, I managed to set up the storage. However, I have an issue with the video(.mp4) files. I have my blobs set as block blobs ( suitable for streaming) The problem that I face is: it takes 10-20 seconds for a video to load on the browser and I can't seek the video (jump forwards/backward).  I browsed the web for a couple of days and I couldn't find much. I found some answers suggesting progressive loading, but in ASP.net. Any idea how to make it in laravel? (sorry if this is not the right place for this question)

**Comment by matthewbdaly** [comment]
Laravel's storage is just a wrapper for Flysystem, and this package is just an adapter class and a service provider to allow the Azure Flysystem adapter to be used with Laravel's storage, which has a fairly limited scope. As such it doesn't actually do all that much. It just instantiates the Flysystem Azure driver and provides a handful of other helpful methods.

It might be that Flysystem supports this, in which case it may be possible to do it through this package. However it's more likely you'll need to work directly with the Azure PHP SDK.

**Comment by brpetrov** [comment]
I see. Thanks for pointing me to these directions, and sorry for posting irrelevant Q here.
