### ISSUE TITLE
Server failed to authenticate the request

### ISSUE THREAD

**Issue by palefire999** [matthewbdaly/laravel-azure-storage#36]
Hi Matthew,

I have been using the laravel-azure-storage to store documents to a General Purpose V2 account for over a month now. Recently, I have observed that it generates the following error when I try to load slightly larger file sizes (like over 3.7 MB). Is this due to some setting on Azure that limits file sizes? I don't have this issue with smaller files around 2 MB. My post_max_size and upload_max_size are set to 10 MB - so that's not an issue.

```
"message": "Fail:\nCode: 403\nValue: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\ndetails (if any): \ufeff<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:d8b2ceac-601e-0016-2f29-fd17e5000000\nTime:2021-02-07T08:17:46.8684637Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request 'CLyWOIZjBxp0dEJuTUHrrazunQc49AP83kFwVLQvz34=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n\n\napplication/x-www-form-urlencoded\nSun, 07 Feb 2021 08:17:46 GMT\n\n\n\n\n\nx-ms-blob-content-type:application/pdf\nx-ms-blob-type:BlockBlob\nx-ms-client-request-id:601fa22ad0de2\nx-ms-version:2017-11-09\n/somename/invoice/iirfiles/USA_latest.pdf'.</AuthenticationErrorDetail></Error>.",
    "exception": "MicrosoftAzure\\Storage\\Common\\Exceptions\\ServiceException",
    "file": "/var/www/html/mir/vendor/microsoft/azure-storage-common/src/Common/Internal/ServiceRestProxy.php",
```

I would really appreciate your advice on this one.

**Comment by matthewbdaly** [comment]
Sorry, I have no idea. This package is just a service provider that makes a Flysystem Azure storage instance available to Laravel so it doesn't deal with the Azure PHP SDK, which looks to be where the issue arises, and my own experience of using Azure was a few years ago.

Given it's a 403 error, suggesting it's something to do with authentication, then if it works for smaller files I think you're probably on the right track when you mention a setting.
