### ISSUE TITLE
SessionHandler

### ISSUE THREAD

**Issue by mohaom** [matthewbdaly/laravel-azure-storage#37]
**Checklist**

Because this project is:

* A custom driver for [Laravel's file storage API](https://laravel.com/docs/8.x/filesystem), and
* Dependent on [Flysystem's Azure driver](https://flysystem.thephpleague.com/v1/docs/adapter/azure/) and, in turn, [the Azure PHP SDK](https://github.com/Azure/azure-storage-php) to do most of the work

The scope of any changes that can be made can be quite limited. If Flysystem, the Laravel storage API or the Azure PHP SDK don't support the feature you want, then it's very unlikely it can be done. As such, please confirm the following:

- [ ] I have checked and confirmed that the Laravel storage API can support this feature
- [ ] I have checked and confirmed that Flysystem can support this feature

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by matthewbdaly** [comment]
You haven't populated the issue template. You need to do so for me to know what your request is.
