### ISSUE TITLE
Prefix for filesystem directory does not apply into Storage::url

### ISSUE THREAD

**Issue by iammh93** [matthewbdaly/laravel-azure-storage#41]
I trying to upload the files to different directory based on environment.
For example:
local - https://storagepath.blob.core.windows.net/container_name/{local}/image.jpg
production- https://storagepath.blob.core.windows.net/container_name/{production}/image.jpg

To do so, this is the config
'azure' => [
    'driver'    => 'azure',
    'name'      => env('AZURE_STORAGE_NAME'),
    'key'       => env('AZURE_STORAGE_KEY'),
    'container' => env('AZURE_STORAGE_CONTAINER'),
    'url'       => env('AZURE_STORAGE_URL'),
    'prefix'    => env('APP_ENV'),
],

So now the files was stored correctly, but i found that when i using Storage::url("image.jpg");
The path returned was "https://storagepath.blob.core.windows.net/container_name/image.jpg" because it using the url in config, 
But url customization also won't worked because it always prepend the container name to the end of url we set and become like "https://storagepath.blob.core.windows.net/container_name/local/container_name/image.jpg"
Of course i can add the prefix like Storage::url("local/image.jpg"); but it seem like not a proper way.

I'm not sure is this a bug or not. Appreciate for any suggestions and comments

**Comment by matthewbdaly** [comment]
As mentioned in the linked PR, I think the best solution is to use separate containers for each environment. This is definitely considered best practice with S3, and logically I see no reason why it shouldn't also be best practice with Azure Blob Storage.

**Comment by iammh93** [comment]
> As mentioned in the linked PR, I think the best solution is to use separate containers for each environment. This is definitely considered best practice with S3, and logically I see no reason why it shouldn't also be best practice with Azure Blob Storage.

Yes, separate containers for each environment should be the proper way and this is my first proposed solution, but from my company perspective, there is no reason to extra pay for local development & staging development, the best approach they provided would be local & staging sharing one container, and production for one, or else is my problem, so i got limited resources and business logic limitation to archive my goal.

Of course there is many hardcoded way can make it worked. From my perspective, I am trying to make all code standard as possible and this is the only way I able figure out. Too bad because of my client internal policy. They didn't allow any services from AWS, so S3 not the alternative option anymore.
BTW if you look into S3 adapter, they do allow the full path control because I get the idea from there.

Anyway is ok the PR is not accepted. I will fork it and point to my branch. Thanks for reply and good work.

**Comment by matthewbdaly** [comment]
As far as I know you shouldn't have to pay extra for separate containers within the same account - you can have as many containers as you like on any one account and the cost is based on the total size of the stored files - it's not affected in any way by the number of containers.
