### ISSUE TITLE
Error with installing the package

### ISSUE THREAD

**Issue by yanalshoubaki** [matthewbdaly/laravel-azure-storage#47]
I have a problem when i want to install the package.

![image](https://user-images.githubusercontent.com/13173362/152227585-b1396a71-30ec-4478-a68f-e9ee368daba0.png)

php version : 8.0
laravel version : 8.65

**Comment by matthewbdaly** [comment]
Sorry, but I don't have the capacity to produce a solution for this issue. It's probably something to do with the dependency on Flysystem's Azure driver.

I'd suggest you consider upgrading to Laravel 9 as the new 2.0 release should work with that.
