### ISSUE TITLE
Azure Storage == Sharepoint

### ISSUE THREAD

**Issue by mgip** [matthewbdaly/laravel-azure-storage#53]
Hi guys,

This library work for use Sharepoint Dcouments as Filesystem ??

Thx

**Comment by matthewbdaly** [comment]
No. It's purely for Azure Blob Storage, nothing else. However, it should be pretty easy to roll your own driver for that.

The Laravel file storage API is built on top of Flysystem, so it can only support filesystems that have Flysystem drivers. It looks like there is a driver for modern versions of Flysystem at https://github.com/homedesignshops/flysystem-sharepoint, and there's a few others about if that's not suitable. Once you have that, you can then create your own driver as described [in the Laravel documentation](https://laravel.com/docs/9.x/filesystem#custom-filesystems), which is how I built this package.
