### ISSUE TITLE
KeyNotSet error when using connection_string

### ISSUE THREAD

**Issue by KasparRosin** [matthewbdaly/laravel-azure-storage#54]
**Describe the bug**
When using `AZURE_STORAGE_CONNECTION_STRING` variable, I receive an 
`Matthewbdaly\ LaravelAzureStorage \ Exceptions \ KeyNotSet`

When using the exact same config in separate variables (`AZURE_STORAGE_URL`, `AZURE_STORAGE_KEY` etc) 
the connection works an no errors are thrown.

**Packages and PHP version**
 - PHP version: 8.1
 - Laravel version: 9.19
 - Version of this package: 2.0.4

**Comment by matthewbdaly** [comment]
Thanks for the bug report! Could you please provide a full stack trace for the exception? There's more than one place it's called from and it would be helpful to know which one it was.

**Comment by KasparRosin** [comment]
Turns out, this was due to my own misconfiguration.
Sorry for the trouble.
