### ISSUE TITLE
Invalid URL generation when using the `prefix` config

### ISSUE THREAD

**Issue by alkin** [matthewbdaly/laravel-azure-storage#55]
**Checklist**

This package is just a wrapper for Flysystem's Azure storage backend to integrate it with Laravel's storage API. As such, many problems users may experience with it may actually be issues with Flysystem, the Azure driver for Flysystem, or Microsoft's PHP SDK. To help eliminate these issues, please confirm the following:

- [x] I'm able to instantiate a Flysystem instance using the same credentials as passed to this package.
- [x] The Flysystem instance works as expected, and the bug I am reporting is not reproducible when interacting directly with Flysystem
- [x] I can instantiate the Microsoft Azure PHP SDK successfully and can interact with my file successfully using that

**Describe the bug**
When using a configured prefix, the URL returned by the `url` method ignores the prefix and is invalid.

**To Reproduce**
1. Config a disk with a prefix: `my_prefix`.
2. Using the package, create a simple file `test.txt` with any content.
3. Generate the URL for the file using the `url()` method.
4. Notice that the URL does not contain the prefix.
5. Open the URL in the browser and confirm that the file is not accessible on the informed URL.
6. Manually add the prefix in the URL and open in the browser.
7. Confirm that the file was created with the correct prefix.

**Expected behavior**
The URL returned form the `url()` method should be correct and contain the prefix configured.

**Packages and PHP version**
Any

**Screenshots**
![image](https://user-images.githubusercontent.com/131324/190841057-0c006df4-e500-4819-92ab-85ed77f0f6c9.png)
![image](https://user-images.githubusercontent.com/131324/190841079-73df9306-a2d0-4da6-a7a0-04f571c2907c.png)
![image](https://user-images.githubusercontent.com/131324/190841086-a3dbcc48-b44f-48cb-bc33-0174dac8eea7.png)
![image](https://user-images.githubusercontent.com/131324/190841106-c08bcf01-377e-4271-bc56-de8bc1886618.png)

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Comment by matthewbdaly** [comment]
I've put together a test case for this (and finally got around to migrating the package from PHPUnit to Pest), and have implemented a fix which resolves the broken test case, and have published it as 2.0.5. However, I don't currently have access to an Azure blob storage account so can't verify it works myself.

Can you confirm this has resolved the issue for you?

**Comment by matthewbdaly** [comment]
Closed due to not hearing back
